create table customer (
	id bigint generated by default as identity (start with 1),
	name varchar(255) not null,
	kana varchar(255) not null,
	zip varchar(7) default null,
	address varchar(255) default null,
	birthday varchar(8) default null,
	phone varchar(12) default null,
	primary key (id)
);

insert into customer (name,kana,zip,address,birthday,phone) values
('初期データ','ショキデータ','1112233','埼玉県和光新','19770403',null);
