--create table customer (
--	id bigint generated by default as identity (start with 1),
--	name varchar(255) not null,
--	kana varchar(255) not null,
--	zip varchar(8) default null,
--	address varchar(255) default null,
--	birthday varchar(10) default null,
--	phone varchar(12) default null,
--	primary key (id)
--);

CREATE TABLE `customer` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `kana` varchar(255) NOT NULL,
  `zip` varchar(8) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `birthday` varchar(10) DEFAULT NULL,
  `phone` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into customer (name,kana,zip,address,birthday,phone) values
('初期データ1','ショキデータ1','111-2233','埼玉県和光新','1977-04-03','00011112222'),
('初期データ2','ショキデータ2','111-2233','埼玉県和光新','1977-04-03',null),
('初期データ3','ショキデータ3','111-2233','埼玉県和光新','1977-04-03',null),
('初期データ4','ショキデータ4','111-2233','埼玉県和光新','1977-04-03',null),
('初期データ5','ショキデータ5','111-2233','埼玉県和光新','1977-04-03',null),
('初期データ6','ショキデータ6','111-2233','埼玉県和光新','1977-04-03',null)
;
